source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'rake'
gem 'pg'
gem 'sinatra-activerecord'

group :test, :development do
  gem 'database_cleaner'
  gem 'pry'
  gem 'capybara'
  gem 'rspec'
  gem 'launchy'
end
